### PR TITLE
 Add toolbar buttons for keyboard actions (closes #22) 

### LINKED ISSUE #22: Add toolbar buttons for keyboard actions
Keyboard actions that are asked for by the activity can be toolbar buttons as well.  These might be placed after the existing buttons, with a separator.

### PR DESCRIPTION
**Pull request by sourabhaa**
Add toolbar buttons for keyboard actions

- [x] Play pause button
- [x] Create new train button
- [x] Restart game button

Fixes #22.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Should be one patch.  (Use of `git bisect` may fail if the code is in error at the point of an attempt.)  Should have more in the commit message, as per our contributing documentation.  Again you have more detail in your pull request comments; ideally the commit message should say everything required, because only the commit message is retained in history.   Pull requests eventually disappear.

**Comment by sourabhaa** [comment]
@quozl , I've updated the commit messages. I thought one liner would be sufficient as the commit contains code for one button. Also, could you guide where I can find the sugar icons? I couldn't find any for reset button icon.

**Comment by quozl** [comment]
Thanks.  If you've not yet learned to merge two commits, and don't have the time, we can squash and merge in GitHub or manually using git.

If you'd like to learn, look at `git rebase -i`.  If you'd like to make sure you don't lose your work so far, take a copy of your git repository and experiment on the copy.

**Comment by sourabhaa** [comment]
Thanks @quozl , I'll give it a try. 
There's one more change I need to make in this PR. I'm adding a toolbar button to restart action, but I'm not able to find any appropriate sugar icon for that. I figured there was `media-playback-pause` and `media-playback-start` icons for pause and play button. If I can find the list of available icons, I could confirm if one exist for restart too. I checked out https://github.com/sugarlabs/sugar-toolkit-gtk3, but couldn't find any. Could you please help with it?

**Comment by quozl** [comment]
I would use the new-game icon, which is contextual rather than common, consisting of an asterisk drawn over something that represents the game being played.

You could just use the activity icon and append the SVG for the asterisk.

Here are some samples discovered on my filesystem;

* https://github.com/sugarlabs/colordeducto/blob/master/icons/new-game.svg new-game
* https://github.com/sugarlabs/cookie-search-activity/blob/master/icons/new-game.svg new-game
* https://github.com/sugarlabs/deducto/blob/master/icons/new-game.svg new-game
* https://github.com/sugarlabs/dimensions/blob/master/icons/new-game.svg new-game
* https://github.com/sugarlabs/dotsAndBoxes/blob/master/icons/new-game.svg new-game
* https://github.com/sugarlabs/flip/blob/master/icons/new-game.svg new-game
* https://github.com/quozl/implode-activity/blob/master/icons/new-game.svg new-game
* https://github.com/sugarlabs/paths/blob/master/icons/new-game.svg new-game
* https://github.com/sugarlabs/paths/blob/master/icons/no-new-game.svg new-game
* https://github.com/sugarlabs/reflection/blob/master/icons/new-game-bilateral.svg new-game
* https://github.com/sugarlabs/reflection/blob/master/icons/new-game-horizontal.svg new-game
* https://github.com/sugarlabs/reflection/blob/master/icons/new-game-vertical.svg new-game
* https://github.com/sugarlabs/sugarchess/blob/master/icons/new-game.svg new-game
* https://github.com/sugarlabs/turtlepond/blob/master/icons/new-game.svg new-game

**Comment by sourabhaa** [comment]
Thanks! I'll implement this.

**Comment by quozl** [comment]
As with anything in software engineering, there are many ways, and not all the ways are easily shared.  :grin:  Remember that SVG files are XML text.

I suggest you try these methods until you find one that works;
* look at one or two of the SVG files using a text editor and see if you can identify the asterisk, and transplant it into your own file,
* use the python3-levenshtein distance package to estimate a textual distance between each of the new-game SVG files, to identify the common component (the asterisk),
* use the python3-moreorless package or other difflib derived algorithms to do the same thing, or;
* draw the asterisk using Inkscape using the existing asterisks as a visual template.
In your commit message, describe the method you chose.

**Comment by sourabhaa** [comment]
@quozl and @chimosky kindly review the MR.

**Comment by quozl** [comment]
Well done.

**Comment by chimosky** [comment]
Tested and reviewed, works as expected. Thanks!

**Pull request merged**
