### PR TITLE
update sugargame to v1.3

### PR DESCRIPTION
**Pull request by ayushnawal**

### CODE REVIEW

**Comment by quozl** [comment]
* [ ] `main= ` should be `main=`, and `modules= ` should be `modules=`,
* [ ] conform to Sugargame v1.3 API, all pygame module intiialisation to be completed in main program, return from game loop on quit, detect GTK stop button.

**Comment by quozl** [comment]
Thanks.  Reviewed as at cfb8b7e.

* [ ] the call to PygameCanvas initialises the whole of Pygame then goes on to initialise the display module of Pygame; it is best to initialise only the modules that are needed,
* [ ] the build_toolbar calls self.show_all, and this is known to induce a race condition; it should not be called if it is not needed at this point in the execution,
* [ ] self.running should be checked just after GTK events are pumped, otherwise a request to exit can cause one more display flip and clock frame delay,
* [ ] there are later changes to sugargame (source code copyright notice and license) that have not been taken into the branch,

**Comment by JuiP** [comment]
Since this branch was not updated for a long time now, I tried updating sugargame to v1.3 in PR #20 
I preferred to sequentially apply and review changes made after version 1.1
- [ ] the build_toolbar calls self.show_all, and this is known to induce a race condition; it should not be called if it is not needed at this point in the execution

Yet to be applied in PR #20

**Comment by JuiP** [comment]
Already merged in #20 .... closes this PR @quozl

**Pull request closed without merging**
