### PR TITLE
Replace box2d binaries with Box2D upstream

### LINKED ISSUE #18: Replace box2d binaries with a Box2D upstream dependency
Related to work already done in Physics and Pippy.

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
Fixes #18  . @quozl KIndly Review.

### CODE REVIEW

**Comment by chimosky** [comment]
Reviewed, can you specify `Box2D` as a dependency in Readme and also give instructions on how to install for debian and fedora.

**Comment by quozl** [comment]
Check out how other activities have specified Box2D in their README.md.

**Comment by Saumya-Mishra9129** [comment]
@chimosky  @quozl I have done with changes in README.md.

**Comment by quozl** [comment]
Thanks.  Reviewed.

**Pull request merged**
