### PR TITLE
more Fixes

### PR DESCRIPTION
**Pull request by JuiP**
Tested till commit 369f664. 
Will work on more improvements

### CODE REVIEW

**Comment by quozl** [comment]
Looks right.  Not tested.

**Comment by Hrishi1999** [comment]
Tested. Fixes #24. I think the activity shouldn't log costs, feels cluttered. What do you say?

**Comment by JuiP** [comment]
Thanks for testing @Hrishi1999 :)

> I think the activity shouldn't log costs, feels cluttered. What do you say?

Yes I agree, I think it was added in the intitial versions for debugging. Also I was looking at Saving and resuming from Journal, it is a lot of work. I had started working, you can have a look at commit 8e326500f924a46781fa6abfb0fb05d4d7e5ca6d . In the commit description I had mentioned few known bugs not fixed in the commit. I would continue working on it, but I was wondering since there are a lot of changes to the activity already, we can include saving data to Journal changes in another release. What do you think @Hrishi1999 @quozl @chimosky ?

**Comment by Hrishi1999** [comment]
Not sure, we could wait for you to complete save to journal feature for the next release. @quozl @chimosky what do you suggest?

**Comment by chimosky** [comment]
> What do you think @Hrishi1999 @quozl @chimosky ?

I agree with @Hrishi1999, we'll wait for you to finish with it.

**Comment by quozl** [comment]
Costs were added for competition in classroom learning environments.  It is so that a teacher can choose the cheapest winning design.  http://wiki.laptop.org/go/Bridge says "Joints and girders have associated costs. The cost of your bridge is shown in the top right of the display. Try and build the cheapest bridge that you can."

For saving and resuming, the Physics activity is the most relevant code example.  As an alternative, an obvious screenshot to journal button could be added.  Sugar already has this as <kbd>alt</kbd>+<kbd>1</kbd>.

**Comment by JuiP** [comment]
Fixes #23 : This issue is blocking release and this activity has a lot of changes since the last release.
@quozl @chimosky @srevinsaju Please review and merge :smile:

**Comment by quozl** [comment]
Thanks.  Reviewed.  Tested.

**Pull request merged**
